module.exports = {
  fileName: '02_hsk1',
  batchKey: 'batch-02-hsk1',
  migrationName: '20260729110000_content_batch_02_hsk1',
  courseKey: 'hsk1',
  slug: 'hsk-1',
  title: 'HSK 1',
  titleZh: 'HSK 一级',
  description: 'A coherent HSK 1 foundation track kept in review pending qualified linguistic approval.',
  descriptionVi: 'Nền tảng giao tiếp và đọc hiểu ở trình độ HSK 1.',
  level: 'beginner',
  orderIndex: 2,
  status: 'review',
  lessonsPerUnit: 3,
  estimatedMinutes: 135,
  objectives: [
    'Hiểu và dùng mẫu câu HSK 1 trong tình huống quen thuộc',
    'Đọc, nói và viết các câu ngắn với trật tự từ cơ bản',
    'Chuẩn bị nền tảng chuyển tiếp lên HSK 2',
  ],
  initialReviewKeys: ['foundation:你好', 'foundation:名字', 'foundation:中国'],
  initialReviewGrammarKeys: ['foundation:called-name'],
  units: [
    {
      slug: 'hsk1-giao-tiep',
      title: 'Giao tiếp ban đầu',
      chapterTitle: 'Chào hỏi và con người',
      descriptionVi: 'Xưng hô, làm quen và mô tả người.',
      objectives: ['Chào hỏi lịch sự', 'Giới thiệu quan hệ và nghề nghiệp'],
    },
    {
      slug: 'hsk1-so-luong-thoi-gian',
      title: 'Số lượng và thời gian',
      chapterTitle: 'Số, ngày và lịch sinh hoạt',
      descriptionVi: 'Hỏi số lượng, tuổi, ngày giờ và hoạt động.',
      objectives: ['Dùng số và lượng từ', 'Nói thời gian và thói quen'],
    },
    {
      slug: 'hsk1-doi-song',
      title: 'Đời sống thường ngày',
      chapterTitle: 'Ăn uống, mua sắm và đi lại',
      descriptionVi: 'Xử lý các nhu cầu đời sống cơ bản.',
      objectives: ['Gọi món và mua hàng', 'Hỏi vị trí và phương tiện'],
    },
  ],
  lessons: [
    {
      slug: 'xung-ho-lich-su',
      title: '您好！— Chào hỏi lịch sự',
      descriptionVi: 'Dùng 您, 请 và cách hỏi họ lịch sự.',
      objectives: ['Chào người lớn tuổi hoặc khách hàng', 'Hỏi họ và làm quen'],
      culturalNote: '贵姓 là cách hỏi họ lịch sự; không dùng để tự nói họ của mình.',
      words: [
        ['您', 'nín', 'ngài, ông/bà (lịch sự)', 'you (polite)', 'đại từ', '您好，请问您贵姓？', 'Nín hǎo, qǐngwèn nín guìxìng?', 'Xin chào, xin hỏi quý danh của ngài?'],
        ['请问', 'qǐngwèn', 'xin hỏi', 'may I ask', 'động từ', '请问，地铁站在哪儿？', 'Qǐngwèn, dìtiě zhàn zài nǎr?', 'Xin hỏi, ga tàu điện ngầm ở đâu?'],
        ['贵姓', 'guìxìng', 'quý danh, họ của ngài', 'your surname', 'cụm từ lịch sự', '请问您贵姓？', 'Qǐngwèn nín guìxìng?', 'Xin hỏi quý danh của ngài?'],
        ['认识', 'rènshi', 'quen, biết', 'to know; meet', 'động từ', '很高兴认识您。', 'Hěn gāoxìng rènshi nín.', 'Rất vui được làm quen với ngài.'],
      ],
      grammar: {
        title: 'Câu hỏi lịch sự với 请问',
        pattern: '请问 + câu hỏi',
        explanationVi: 'Đặt 请问 trước câu hỏi để mở lời lịch sự.',
        correct: '请问您贵姓？',
        pinyin: 'Qǐngwèn nín guìxìng?',
        meaningVi: 'Xin hỏi quý danh của ngài?',
        question: 'Câu nào hỏi họ một cách lịch sự?',
        wrong: ['您贵姓请问？', '贵姓您不请问。'],
      },
      tokens: ['请问', '您', '贵姓', '？'],
    },
    {
      slug: 'ban-be-va-nghe-nghiep',
      title: '同学和老师 — Bạn học và giáo viên',
      descriptionVi: 'Giới thiệu quan hệ và nghề nghiệp gần gũi.',
      objectives: ['Nói ai là ai', 'Dùng 的 để chỉ quan hệ'],
      words: [
        ['老师', 'lǎoshī', 'giáo viên', 'teacher', 'danh từ', '王老师教我们汉语。', 'Wáng lǎoshī jiāo wǒmen Hànyǔ.', 'Thầy Vương dạy chúng tôi tiếng Trung.'],
        ['同学', 'tóngxué', 'bạn học', 'classmate', 'danh từ', '她是我的同学。', 'Tā shì wǒ de tóngxué.', 'Cô ấy là bạn học của tôi.'],
        ['先生', 'xiānsheng', 'ông, ngài', 'Mr.; sir', 'danh từ', '李先生是医生。', 'Lǐ xiānsheng shì yīshēng.', 'Ông Lý là bác sĩ.'],
        ['医生', 'yīshēng', 'bác sĩ', 'doctor', 'danh từ', '我姐姐是医生。', 'Wǒ jiějie shì yīshēng.', 'Chị gái tôi là bác sĩ.'],
      ],
      grammar: {
        title: 'Quan hệ sở hữu với 的',
        pattern: 'A + 的 + B',
        explanationVi: '的 nối người sở hữu hoặc quan hệ với danh từ đứng sau.',
        correct: '她是我的同学。',
        pinyin: 'Tā shì wǒ de tóngxué.',
        meaningVi: 'Cô ấy là bạn học của tôi.',
        question: 'Câu nào nói “Cô ấy là bạn học của tôi”?',
        wrong: ['她我的同学是。', '她是我同学的。'],
      },
      tokens: ['她', '是', '我', '的', '同学', '。'],
    },
    {
      slug: 'hoi-ai-va-o-dau',
      title: '谁在哪儿？— Ai ở đâu?',
      descriptionVi: 'Hỏi người và vị trí bằng 谁, 哪儿.',
      objectives: ['Đặt câu hỏi về người', 'Nói vị trí với 在'],
      words: [
        ['谁', 'shéi', 'ai', 'who', 'đại từ nghi vấn', '门口的人是谁？', 'Ménkǒu de rén shì shéi?', 'Người ở cửa là ai?'],
        ['哪儿', 'nǎr', 'đâu, nơi nào', 'where', 'đại từ nghi vấn', '你的学校在哪儿？', 'Nǐ de xuéxiào zài nǎr?', 'Trường của bạn ở đâu?'],
        ['学校', 'xuéxiào', 'trường học', 'school', 'danh từ', '学校离我家很近。', 'Xuéxiào lí wǒ jiā hěn jìn.', 'Trường học rất gần nhà tôi.'],
        ['医院', 'yīyuàn', 'bệnh viện', 'hospital', 'danh từ', '医院在银行旁边。', 'Yīyuàn zài yínháng pángbiān.', 'Bệnh viện ở cạnh ngân hàng.'],
      ],
      grammar: {
        title: 'Vị trí với 在',
        pattern: 'chủ ngữ + 在 + địa điểm',
        explanationVi: '在 đứng trước địa điểm để nói người hoặc vật đang ở đâu.',
        correct: '医院在银行旁边。',
        pinyin: 'Yīyuàn zài yínháng pángbiān.',
        meaningVi: 'Bệnh viện ở cạnh ngân hàng.',
        question: 'Câu nào có trật tự vị trí đúng?',
        wrong: ['医院银行在旁边。', '在医院旁边银行。'],
      },
      tokens: ['医院', '在', '银行', '旁边', '。'],
    },
    {
      slug: 'so-luong-va-tuoi',
      title: '几岁？— Số lượng và tuổi',
      descriptionVi: 'Hỏi tuổi và số lượng nhỏ bằng 几.',
      objectives: ['Hỏi tuổi trẻ em', 'Dùng lượng từ 个'],
      words: [
        ['几', 'jǐ', 'mấy, bao nhiêu', 'how many', 'đại từ nghi vấn', '你有几个汉语老师？', 'Nǐ yǒu jǐ ge Hànyǔ lǎoshī?', 'Bạn có mấy giáo viên tiếng Trung?'],
        ['岁', 'suì', 'tuổi', 'years old', 'lượng từ', '我弟弟八岁。', 'Wǒ dìdi bā suì.', 'Em trai tôi tám tuổi.'],
        ['个', 'gè', 'cái, người (lượng từ chung)', 'general measure word', 'lượng từ', '桌上有三个苹果。', 'Zhuō shàng yǒu sān ge píngguǒ.', 'Trên bàn có ba quả táo.'],
        ['有', 'yǒu', 'có', 'to have; there is', 'động từ', '我家有四口人。', 'Wǒ jiā yǒu sì kǒu rén.', 'Nhà tôi có bốn người.'],
      ],
      grammar: {
        title: 'Câu tồn tại và sở hữu với 有',
        pattern: 'chủ ngữ + 有 + số lượng + danh từ',
        explanationVi: '有 diễn tả sở hữu hoặc sự tồn tại; phủ định là 没有.',
        correct: '我家有四口人。',
        pinyin: 'Wǒ jiā yǒu sì kǒu rén.',
        meaningVi: 'Nhà tôi có bốn người.',
        question: 'Câu nào nói đúng “Nhà tôi có bốn người”?',
        wrong: ['我家是四口人有。', '我有家四人不。'],
      },
      tokens: ['我家', '有', '四', '口', '人', '。'],
    },
    {
      slug: 'ngay-va-thu',
      title: '星期几？— Ngày và thứ',
      descriptionVi: 'Nói ngày tháng và thứ trong tuần.',
      objectives: ['Hỏi hôm nay thứ mấy', 'Nói ngày theo trật tự năm-tháng-ngày'],
      words: [
        ['星期', 'xīngqī', 'tuần; thứ', 'week; weekday', 'danh từ', '今天星期五。', 'Jīntiān xīngqīwǔ.', 'Hôm nay là thứ Sáu.'],
        ['月', 'yuè', 'tháng', 'month', 'danh từ', '我的生日是五月九号。', 'Wǒ de shēngrì shì wǔ yuè jiǔ hào.', 'Sinh nhật tôi là ngày 9 tháng 5.'],
        ['号', 'hào', 'ngày (khẩu ngữ)', 'day of month', 'danh từ', '明天是三月十号。', 'Míngtiān shì sān yuè shí hào.', 'Ngày mai là mùng 10 tháng 3.'],
        ['生日', 'shēngrì', 'sinh nhật', 'birthday', 'danh từ', '祝你生日快乐！', 'Zhù nǐ shēngrì kuàilè!', 'Chúc bạn sinh nhật vui vẻ!'],
      ],
      grammar: {
        title: 'Trật tự ngày tháng',
        pattern: 'tháng + 月 + ngày + 号',
        explanationVi: 'Tiếng Trung nói đơn vị lớn trước đơn vị nhỏ: tháng rồi đến ngày.',
        correct: '我的生日是五月九号。',
        pinyin: 'Wǒ de shēngrì shì wǔ yuè jiǔ hào.',
        meaningVi: 'Sinh nhật tôi là ngày 9 tháng 5.',
        question: 'Câu nào có trật tự ngày tháng đúng?',
        wrong: ['我的生日是九号五月。', '五月我的九生日号。'],
      },
      tokens: ['我', '的', '生日', '是', '五月', '九号', '。'],
    },
    {
      slug: 'kha-nang-va-so-thich',
      title: '会不会？— Khả năng và sở thích',
      descriptionVi: 'Nói biết làm gì và thích hoạt động nào.',
      objectives: ['Dùng 会 cho kỹ năng đã học', 'Dùng 喜欢 cho sở thích'],
      words: [
        ['会', 'huì', 'biết, có thể (kỹ năng)', 'can; know how to', 'động từ năng nguyện', '我会说一点儿汉语。', 'Wǒ huì shuō yìdiǎnr Hànyǔ.', 'Tôi biết nói một chút tiếng Trung.'],
        ['说', 'shuō', 'nói', 'to speak; say', 'động từ', '请慢一点儿说。', 'Qǐng màn yìdiǎnr shuō.', 'Xin hãy nói chậm một chút.'],
        ['喜欢', 'xǐhuan', 'thích', 'to like', 'động từ', '她喜欢看中国电影。', 'Tā xǐhuan kàn Zhōngguó diànyǐng.', 'Cô ấy thích xem phim Trung Quốc.'],
        ['看', 'kàn', 'xem, nhìn, đọc', 'to look; watch; read', 'động từ', '晚上我看书。', 'Wǎnshang wǒ kàn shū.', 'Buổi tối tôi đọc sách.'],
      ],
      grammar: {
        title: 'Khả năng đã học với 会',
        pattern: 'chủ ngữ + 会 + động từ',
        explanationVi: '会 đứng trước động từ để nói kỹ năng có được nhờ học tập.',
        correct: '我会说一点儿汉语。',
        pinyin: 'Wǒ huì shuō yìdiǎnr Hànyǔ.',
        meaningVi: 'Tôi biết nói một chút tiếng Trung.',
        question: 'Câu nào diễn tả kỹ năng nói tiếng Trung?',
        wrong: ['我说会汉语一点儿。', '会我一点儿说汉语。'],
      },
      tokens: ['我', '会', '说', '一点儿', '汉语', '。'],
    },
    {
      slug: 'an-uong-va-mua-sam',
      title: '想吃什么？— Ăn uống và mua sắm',
      descriptionVi: 'Nói nhu cầu, gọi món và hỏi giá đơn giản.',
      objectives: ['Dùng 想 để nói mong muốn', 'Dùng 这/那 chỉ món đồ'],
      words: [
        ['想', 'xiǎng', 'muốn; nghĩ', 'to want; think', 'động từ năng nguyện', '我想喝一杯热茶。', 'Wǒ xiǎng hē yì bēi rè chá.', 'Tôi muốn uống một cốc trà nóng.'],
        ['喝', 'hē', 'uống', 'to drink', 'động từ', '天气热，多喝水。', 'Tiānqì rè, duō hē shuǐ.', 'Trời nóng, hãy uống nhiều nước.'],
        ['苹果', 'píngguǒ', 'quả táo', 'apple', 'danh từ', '这些苹果很甜。', 'Zhèxiē píngguǒ hěn tián.', 'Những quả táo này rất ngọt.'],
        ['块', 'kuài', 'đồng; miếng', 'yuan; piece', 'lượng từ', '这杯咖啡二十块。', 'Zhè bēi kāfēi èrshí kuài.', 'Cốc cà phê này giá hai mươi tệ.'],
      ],
      grammar: {
        title: 'Mong muốn với 想',
        pattern: 'chủ ngữ + 想 + động từ/tân ngữ',
        explanationVi: '想 diễn tả mong muốn tương đối nhẹ và lịch sự.',
        correct: '我想喝一杯热茶。',
        pinyin: 'Wǒ xiǎng hē yì bēi rè chá.',
        meaningVi: 'Tôi muốn uống một cốc trà nóng.',
        question: 'Câu nào nói mong muốn uống trà nóng?',
        wrong: ['我喝想热茶一杯。', '想我一杯不热茶。'],
      },
      tokens: ['我', '想', '喝', '一杯', '热茶', '。'],
    },
    {
      slug: 'di-lai-va-vi-tri',
      title: '怎么去？— Đi lại và vị trí',
      descriptionVi: 'Hỏi cách đi và xác định vị trí gần.',
      objectives: ['Hỏi phương thức bằng 怎么', 'Nói vị trí với 前面/后面'],
      words: [
        ['怎么', 'zěnme', 'thế nào, bằng cách nào', 'how', 'đại từ nghi vấn', '我们怎么去火车站？', 'Wǒmen zěnme qù huǒchēzhàn?', 'Chúng ta đi ga tàu hỏa bằng cách nào?'],
        ['公共汽车', 'gōnggòng qìchē', 'xe buýt', 'bus', 'danh từ', '我每天坐公共汽车上班。', 'Wǒ měitiān zuò gōnggòng qìchē shàngbān.', 'Mỗi ngày tôi đi xe buýt đến chỗ làm.'],
        ['前面', 'qiánmiàn', 'phía trước', 'in front', 'danh từ phương vị', '超市就在前面。', 'Chāoshì jiù zài qiánmiàn.', 'Siêu thị ở ngay phía trước.'],
        ['后面', 'hòumiàn', 'phía sau', 'behind', 'danh từ phương vị', '学校后面有一个公园。', 'Xuéxiào hòumiàn yǒu yí ge gōngyuán.', 'Phía sau trường có một công viên.'],
      ],
      grammar: {
        title: 'Hỏi cách thức bằng 怎么',
        pattern: 'chủ ngữ + 怎么 + động từ',
        explanationVi: '怎么 đứng trước động từ để hỏi cách thực hiện hành động.',
        correct: '我们怎么去火车站？',
        pinyin: 'Wǒmen zěnme qù huǒchēzhàn?',
        meaningVi: 'Chúng ta đi ga tàu hỏa bằng cách nào?',
        question: 'Câu nào hỏi cách đi đến ga tàu hỏa?',
        wrong: ['我们去怎么火车站？', '怎么火车站我们不去？'],
      },
      tokens: ['我们', '怎么', '去', '火车站', '？'],
    },
  ],
};
